export default theme => ({
  pubAssetInfoContainer: {
    height: '100%',
    border: '1px solid #E6EAEE',
    borderRadius: '0 4px 4px 0',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  pubAssetLabelPart: {
    width: '100%',
    height: '10%',
    position: 'relative',
  },
  pubAssetInfoLabel: {
    color: '#354052',
    fontSize: '18px',
    marginLeft: '20px',
    marginBottom: '20px',
  },
  pubAssetBoxesContainer: {
    marginTop: '0px',
    marginBottom: '20px',
    width: '100%',
    height: '90%',
    '@media screen and (max-width: 1200px)': {
      marginBottom: '20px',
    }
  },
  pubAssetInfoBoxElement: {
    height: '130px',
    width: '125px',
    border: '1px solid #DFE2E5',
    borderRadius: '2.39px',
    backgroundColor: '#FFFFFF',
    margin: '40px 5px 0px 10px',
    padding: '5px',
  },
  pubAssetBoxLabelContainer: {
    height: '40%',
    position: 'relative',
  },
  pubAssetBoxLabel: {
    marginTop: '10px',
    marginLeft: '10px',
    width: '87px',
    textAlign: 'left',
    color: '#91A1B3',
    fontSize: '14px',
    fontWeight: '600',
    '& > span': {
      position: 'absolute',
      width: 'auto',
      height: 'auto',
      top: -5,
      right: -2,
    }
  },
  pubAssetBoxText: {
    marginTop: '10px',
    textAlign: 'center',
    color: '#354052',
    fontSize: '18px',
    maxHeight: '30px',
  },
  pubAssetValidWrapper: {
    position: 'absolute',
    marginLeft: '5%',
    marginTop: '-5px',
    right: '20px',
    top: '15px',
  },
  assetValid: {
    display: 'inline',
    backgroundColor: '#45B854',
    color: '#ffffff',
    borderRadius: '4px',
    padding: '2px',
    width: '72px',
    height: '26px',
    textAlign: 'center',
    top: '9px',
    position: 'relative',
  },
  assetPending: {
    display: 'inline',
    backgroundColor: '#F7981C',
    color: '#ffffff',
    borderRadius: '4px',
    padding: '2px',
    // width: '72px',
    height: '26px',
    textAlign: 'center',
    top: '9px',
    position: 'relative',
  },
  assetDeclined: {
    display: 'inline',
    backgroundColor: '#ff0000',
    color: '#ffffff',
    borderRadius: '4px',
    padding: '2px',
    width: '72px',
    height: '26px',
    textAlign: 'center',
    top: '9px',
    position: 'relative',
  },
  assetRegistered: {
    display: 'inline',
    backgroundColor: '#3366ff',
    color: '#ffffff',
    borderRadius: '4px',
    padding: '2px',
    width: '72px',
    height: '26px',
    textAlign: 'center',
    top: '9px',
    position: 'relative',
  },
  buttonsContainer: {
    marginTop: '30px',
  },
  approveButton: {
    fontWeight: 600,
    backgroundColor: '#ffeb3b',
    marginLeft: 'auto',
    marginRight: '50px',
    '&:hover': {
      backgroundColor: '#ffeb3b',
    },
  },
  declineButton: {
    color: 'white',
    fontWeight: 600,
    backgroundColor: '#ff0000',
    marginRight: 'auto',
    marginLeft: '50px',
    '&:hover': {
      backgroundColor: '#ff0000',
    },
  },
})
